Repository DeveloperAcademy-POSTECH/2025-C4-A14-COCOMONG, pull requests merged in 2025-07, with the labels that each got.

#7 🎨 Design/#4 - 사이클 선택 뷰 UI 구현
  Beat100/Beat100.xcodeproj/project.pbxproj
  Beat100/WatchBeat100 Watch App/App/WatchBeat100App.swift
  Beat100/WatchBeat100 Watch App/Resources/Extension/Font+Extensions.swift
  Beat100/WatchBeat100 Watch App/Resources/Presentation/ChooseCycle/ChooseCycleInfoView.swift
  Beat100/WatchBeat100 Watch App/Resources/Presentation/ChooseCycle/ChooseCycleView.swift
Labels: 🎨 Design

#11 ✨ Feat/#8 - iOS-Watch Connectivity 구현
  Beat100/Beat100.xcodeproj/project.pbxproj
  Beat100/Beat100/Resources/Presentation/Countdown/CountdownView.swift
  Beat100/Beat100/Resources/Presentation/Dummy/PracticeSyncView.swift
  Beat100/Beat100/Resources/Service/Manager/WatchConnectivityManager.swift
  Beat100/Beat100/Resources/Service/Manager/c1.swift
  Beat100/WatchBeat100 Watch App/Resources/Presentation/ChooseCycle/ChooseCycleInfoView.swift
  Beat100/WatchBeat100 Watch App/Resources/Presentation/ChooseCycle/ChooseCycleView.swift
  Beat100/WatchBeat100 Watch App/Resources/Presentation/Dummy/WatchConnectView.swift
  Beat100/WatchBeat100 Watch App/Resources/Service/Manager/WatchConnectivityManager.swift
  Beat100/WatchBeat100 Watch App/Resources/Service/Manager/c5.swift
Labels: ✨ Feature

#12 🍀 Chore/#5 - CoreData 모델 추가
  Beat100/Beat100/Beat100.xcdatamodeld/Beat100.xcdatamodel/contents
  Beat100/Beat100/Resources/Models/Beat100.xcdatamodeld/.xccurrentversion
  Beat100/Beat100/Resources/Models/Beat100.xcdatamodeld/Beat100.xcdatamodel/contents
  Beat100/Beat100/Resources/Models/BpmPoint+Convenience.swift
  Beat100/Beat100/Resources/Models/CprCycle+Convenience.swift
  Beat100/Beat100/Resources/Models/CprReport+Convenience.swift
  Beat100/Beat100/Resources/Models/CycleAccuracy+Convenience.swift
  Beat100/Beat100/Resources/Models/DepthPoint+Convenience.swift
  Beat100/Beat100/Resources/Models/Persistence.swift
  Beat100/Beat100/Resources/Models/TotalAccuracy+Convenience.swift
  Beat100/Beat100/Resources/Presentation/ContentView.swift
Labels: 📂 Chore

#29 🎨 Design/#22 - 리포트 홈 내의 ReportSummaryCardView 구현
  Beat100/Beat100.xcodeproj/project.pbxproj
  Beat100/Beat100/Assets.xcassets/Colorchip/Pink/beat_grad_pink.colorset/Contents.json
  Beat100/Beat100/Resources/Common/Components/CustomCircleProgressView.swift
  Beat100/Beat100/Resources/Common/Components/CustomGradientCircle.swift
  Beat100/Beat100/Resources/Common/Components/c3.swift
  Beat100/Beat100/Resources/Presentation/Report/ReportDetailView.swift
  Beat100/Beat100/Resources/Presentation/Report/ReportHomeView.swift
  Beat100/Beat100/Resources/Presentation/Report/ReportSummaryCardView.swift
Labels: 🎨 Design

#32 🎨 Design/#19 - CountdownAnimationView 구현
  Beat100/Beat100.xcodeproj/project.pbxproj
  Beat100/Beat100/Resources/Common/Components/CustomCircleProgressView.swift
  Beat100/Beat100/Resources/Common/Components/CustomGradientCircle.swift
  Beat100/Beat100/Resources/Presentation/Countdown/CountdownAnimationView.swift
  Beat100/Beat100/Resources/Presentation/Countdown/CountdownView.swift
  Beat100/Beat100/Resources/Presentation/Dummy/PracticeSyncView.swift
  Beat100/WatchBeat100 Watch App/Assets.xcassets/Colorchip/beat_grad_pink.colorset/Contents.json
  Beat100/WatchBeat100 Watch App/Resources/Presentation/Dummy/WatchConnectView.swift
Labels: 🎨 Design

#33 🎨 Design/#31 - 가이드 홈 구현
  Beat100/Beat100.xcodeproj/project.pbxproj
  Beat100/Beat100/Assets.xcassets/Images/common/cpr_heart.imageset/Contents.json
  Beat100/Beat100/Assets.xcassets/Images/common/cpr_heart.imageset/자산 8@3x 1.pdf
  Beat100/Beat100/Resources/Common/Components/LargeCard.swift
  Beat100/Beat100/Resources/Presentation/Guide/GuideHomeView.swift
  Beat100/Beat100/Resources/Presentation/MainTabView.swift
  Beat100/Beat100/Resources/Util/Constants.swift
Labels: 🎨 Design

#35 ♻️ Refactor/#34 - Navigation 방식 변경
  Beat100/Beat100/Resources/Common/Components/LargeButton.swift
  Beat100/Beat100/Resources/Common/Components/LargeButtonStyle.swift
  Beat100/Beat100/Resources/Common/Enum/LargeButtonType.swift
  Beat100/Beat100/Resources/Common/Enum/MeasurementGuide.swift
  Beat100/Beat100/Resources/Presentation/Guide/GuideHomeView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/AppMechanismGuideView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/CompressionPositionGuideView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/MeasurementStartView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/RateAndDepthGuideView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/WatchWearingGuideView.swift
  Beat100/Beat100/Resources/Presentation/Navigation/NavigationManager.swift
Labels: 🔨 Fix, ♻️ Refactor

#42 🎨 Design/#36 - MeasuringCompleteView 구현
  Beat100/Beat100.xcodeproj/project.pbxproj
  Beat100/Beat100/Resources/Common/Components/BouncingDotsView.swift
  Beat100/Beat100/Resources/Presentation/Measuring/MeasuringCompleteView.swift
  Beat100/Beat100/Resources/Util/Config.swift
Labels: 🎨 Design

#44 🎨 Design/#23 - ReportDetailView 구현
  Beat100/Beat100/Resources/Models/Beat100.xcdatamodeld/Beat100.xcdatamodel/contents
  Beat100/Beat100/Resources/Models/CprCycle+Convenience.swift
  Beat100/Beat100/Resources/Models/CprReport+Convenience.swift
  Beat100/Beat100/Resources/Presentation/MainTab/MainTabView.swift
  Beat100/Beat100/Resources/Presentation/Report/ReportDetail/CycleSummaryCellView.swift
  Beat100/Beat100/Resources/Presentation/Report/ReportDetail/DepthSectionView.swift
  Beat100/Beat100/Resources/Presentation/Report/ReportDetail/DetailSectionView.swift
  Beat100/Beat100/Resources/Presentation/Report/ReportDetail/PaceSectionView.swift
  Beat100/Beat100/Resources/Presentation/Report/ReportDetail/ReportDetailView.swift
  Beat100/Beat100/Resources/Presentation/Report/ReportDetail/SummarySectionView.swift
  Beat100/Beat100/Resources/Presentation/Report/ReportDetailView.swift
  Beat100/Beat100/Resources/Presentation/Report/ReportHome/ExplainPressureCardView.swift
  Beat100/Beat100/Resources/Presentation/Report/ReportHome/ReportHomeView.swift
  Beat100/Beat100/Resources/Presentation/Report/ReportHome/ReportSummaryCardView.swift
  Beat100/Beat100/Resources/Util/Constants.swift
Labels: 🎨 Design, ✨ Feature

#49 🎨 Design/#47 - CPR 가이드 및 측정 가이드 디자인 변경
  Beat100/Beat100/Resources/Common/Components/TopBar.swift
  Beat100/Beat100/Resources/Presentation/Guide/CPRGuide/CPRGuideView.swift
  Beat100/Beat100/Resources/Presentation/Guide/GuideHomeView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/AppMechanismGuideView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/CompressionPositionGuideView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/MeasurementStartView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/RateAndDepthGuideView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/WatchWearingGuideView.swift
  Beat100/Beat100/Resources/Util/Constants.swift
Labels: 🎨 Design, ✨ Feature

#53 ♻️ Refactor/#48 - Measuring 관련 뷰 리팩토링
  Beat100/Beat100.xcodeproj/project.pbxproj
  Beat100/Beat100/App/AppState.swift
  Beat100/Beat100/App/Beat100App.swift
  Beat100/Beat100/Resources/Presentation/Dummy/SourceCheckView.swift
  Beat100/Beat100/Resources/Presentation/MainTab/MainTabView.swift
  Beat100/Beat100/Resources/Presentation/Measuring/MeasuringCompleteView.swift
  Beat100/Beat100/Resources/Presentation/Measuring/MeasuringView.swift
  Beat100/Beat100/Resources/Presentation/iOSMeasuringFlow/iOSMeasuringFlowView.swift
  Beat100/Beat100/Resources/Util/Config.swift
  Beat100/Beat100/Resources/Util/NotificationFunction.swift
  Beat100/WatchBeat100 Watch App/Resources/Common/Components/DisabledToolbar.swift
  Beat100/WatchBeat100 Watch App/Resources/Common/Components/PickerGradientBackgroundColor.swift
  Beat100/WatchBeat100 Watch App/Resources/Common/Components/PickerGradientOverlay.swift
  Beat100/WatchBeat100 Watch App/Resources/Presentation/ChooseCycle/ChooseCycleView.swift
  Beat100/WatchBeat100 Watch App/Resources/Presentation/Finish/FinishView.swift
  Beat100/WatchBeat100 Watch App/Resources/Presentation/MeasuringFlow/MeasuringFlowView.swift
  Beat100/WatchBeat100-Watch-App-Info.plist
Labels: ♻️ Refactor

#52 🎨 Design/#50 - CPR 측정 가이드 애니메이션 추가
  Beat100/Beat100.xcodeproj/project.pbxproj
  Beat100/Beat100.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Beat100/Beat100/Resources/Presentation/Guide/CPRGuide/CPRGuideView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/AppMechanismGuideView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/CompressionPositionGuideView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/MeasurementStartView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/RateAndDepthGuideView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/WatchWearingGuideView.swift
  Beat100/Beat100/Sources/Rive/guide1.riv
  Beat100/Beat100/Sources/Rive/guide2.riv
  Beat100/Beat100/Sources/Rive/guide3.riv
  Beat100/Beat100/Sources/Rive/guide4.riv
  Beat100/Beat100/Sources/Rive/guide5.riv
Labels: 📂 Chore, 🎨 Design

#57 🐛 Bug/#56 - CPR 측정 가이드에서 버튼 동작 영역 버그 수정
  Beat100/Beat100.xcodeproj/project.pbxproj
  Beat100/Beat100/Assets.xcassets/Images/common/Beat100Title.imageset/Beat100Title.svg
  Beat100/Beat100/Assets.xcassets/Images/common/Beat100Title.imageset/Contents.json
  Beat100/Beat100/Resources/Common/Components/Buttons/LargeButtonStyle.swift
  Beat100/Beat100/Resources/Common/Components/Buttons/SmallButton.swift
  Beat100/Beat100/Resources/Common/Components/Card/ConditionalLargeCard.swift
  Beat100/Beat100/Resources/Common/Components/Card/ExclamationIcon.swift
  Beat100/Beat100/Resources/Common/Components/Card/LargeCard.swift
  Beat100/Beat100/Resources/Common/Components/ProgressBar/CustomCircleProgressView.swift
  Beat100/Beat100/Resources/Common/Components/ProgressBar/CustomGradientCircle.swift
  Beat100/Beat100/Resources/Common/Components/ProgressBar/CustomReportGradientCircle.swift
  Beat100/Beat100/Resources/Common/Components/Toolbars/BackCancelToolbar.swift
  Beat100/Beat100/Resources/Common/Components/Toolbars/CustomNavigationBar.swift
  Beat100/Beat100/Resources/Presentation/Guide/GuideHomeView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/AppMechanismGuideView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/CompressionPositionGuideView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/MeasurementStartView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/RateAndDepthGuideView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/WatchWearingGuideView.swift
  Beat100/Beat100/Resources/Util/Constants.swift
Labels: 🔨 Fix

#65 🍀Chore/#62 - Xcode TestFlight 배포용 세팅
  Beat100/Beat100.xcodeproj/project.pbxproj
  Beat100/Beat100/Resources/Common/Components/Measuring/HeartIconView.swift
  Beat100/WatchBeat100 Watch App/Assets.xcassets/Profile.imageset/Contents.json
  Beat100/WatchBeat100 Watch App/Assets.xcassets/Profile.imageset/Profile.pdf
  Beat100/WatchBeat100 Watch App/Resources/Presentation/ChooseCycle/WatchStartView.swift
  Beat100/WatchBeat100 Watch App/Resources/Presentation/Finish/FinishView.swift
  Beat100/WatchBeat100 Watch App/WatchBeat100 Watch App.entitlements
Labels: 📂 Chore

#73 🎨 Design/#68 - iOS 디자인 QA 사항 반영
  Beat100/Beat100.xcodeproj/project.pbxproj
  Beat100/Beat100/Assets.xcassets/Images/common/AppleWatch.imageset/Contents.json
  Beat100/Beat100/Assets.xcassets/Images/common/AppleWatch.imageset/Group 291.svg
  Beat100/Beat100/Assets.xcassets/Images/common/Beat100Title.imageset/Beat100Title.svg
  Beat100/Beat100/Assets.xcassets/Images/common/Profile.imageset/Contents.json
  Beat100/Beat100/Assets.xcassets/Images/common/appleWatch.imageset/Contents.json
  Beat100/Beat100/Assets.xcassets/Images/common/appleWatch.imageset/appleWatch.png
  Beat100/Beat100/Assets.xcassets/Images/common/beat100Title.imageset/Contents.json
  Beat100/Beat100/Assets.xcassets/Images/common/beat100Title.imageset/beat100Title.svg
  Beat100/Beat100/Assets.xcassets/Images/common/cpr_heart.imageset/Contents.json
  Beat100/Beat100/Assets.xcassets/Images/common/cpr_heart.imageset/cpr_heart.pdf
  Beat100/Beat100/Assets.xcassets/Images/common/cpr_heart.imageset/cpr_heart.svg
  Beat100/Beat100/Assets.xcassets/Images/cpr_guideline/guide1.imageset/Contents.json
  Beat100/Beat100/Assets.xcassets/Images/cpr_guideline/guide1.imageset/guide1.svg
  Beat100/Beat100/Assets.xcassets/Images/cpr_guideline/guide1.imageset/guide1@3x.pdf
  Beat100/Beat100/Assets.xcassets/Images/cpr_guideline/guide2.imageset/Contents.json
  Beat100/Beat100/Assets.xcassets/Images/cpr_guideline/guide2.imageset/guide2.svg
  Beat100/Beat100/Assets.xcassets/Images/cpr_guideline/guide2.imageset/guide2@3x.pdf
  Beat100/Beat100/Assets.xcassets/Images/cpr_guideline/guide3.imageset/Contents.json
  Beat100/Beat100/Assets.xcassets/Images/cpr_guideline/guide3.imageset/guide3.svg
  Beat100/Beat100/Assets.xcassets/Images/cpr_guideline/guide3.imageset/guide3@3x.pdf
  Beat100/Beat100/Assets.xcassets/Images/cpr_guideline/guide4.imageset/Contents.json
  Beat100/Beat100/Assets.xcassets/Images/cpr_guideline/guide4.imageset/guide4.svg
  Beat100/Beat100/Assets.xcassets/Images/cpr_guideline/guide4.imageset/guide4@3x.pdf
  Beat100/Beat100/Assets.xcassets/Images/cpr_guideline/guide5.imageset/Contents.json
  Beat100/Beat100/Assets.xcassets/Images/cpr_guideline/guide5.imageset/guide5.svg
  Beat100/Beat100/Assets.xcassets/Images/cpr_guideline/guide5.imageset/guide5@3x.pdf
  Beat100/Beat100/Resources/Common/Components/Card/ConditionalLargeCard.swift
  Beat100/Beat100/Resources/Common/Components/Card/LargeCard.swift
  Beat100/Beat100/Resources/Presentation/Guide/CPRGuide/CPRGuideView.swift
  Beat100/Beat100/Resources/Presentation/Guide/CPRGuide/CPRStep.swift
  Beat100/Beat100/Resources/Presentation/Guide/GuideHomeView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/AppMechanismGuideView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/CompressionPositionGuideView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/MeasurementStartView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/RateAndDepthGuideView.swift
  Beat100/Beat100/Resources/Presentation/Guide/MeasurementGuide/WatchWearingGuideView.swift
  Beat100/Beat100/Resources/Util/Constants.swift
  Beat100/Beat100/Sources/Rive/guide4.riv
Labels: 🎨 Design

#74 ✨Feat/#70 - Workout Session 및 HealthKit 적용
  Beat100/Beat100.xcodeproj/project.pbxproj
  Beat100/Beat100/App/Beat100App.swift
  Beat100/Beat100/Beat100.entitlements
  Beat100/Beat100/Resources/Presentation/Measuring/MeasuringView.swift
  Beat100/Beat100/Resources/Service/Manager/HealthKitManager.swift
  Beat100/WatchBeat100 Watch App/Resources/Presentation/MeasuringFlow/MeasuringFlowView.swift
  Beat100/WatchBeat100 Watch App/Resources/Service/Manager/WorkoutManager.swift
Labels: ✨ Feature

#76 🎨 Design/#75 - 2차 WatchOS 디자인 QA 적용
  Beat100/Beat100.xcodeproj/project.pbxproj
  Beat100/Beat100/Resources/Common/Components/Measuring/CountdownCircle.swift
  Beat100/Beat100/Resources/Presentation/Measuring/MeasuringView.swift
  Beat100/Beat100/Resources/Presentation/Measuring/MeasuringViewModel.swift
  Beat100/Beat100/Resources/Util/Config.swift
  Beat100/WatchBeat100 Watch App/Resources/Common/Components/LargeActionButton.swift
  Beat100/WatchBeat100 Watch App/Resources/Presentation/ChooseCycle/ChooseCycleView.swift
  Beat100/WatchBeat100 Watch App/Resources/Presentation/ChooseCycle/WatchStartView.swift
  Beat100/WatchBeat100 Watch App/Resources/Presentation/Finish/FinishView.swift
Labels: 🎨 Design
